database:
  address: localhost
  port: 1488
  name: topdb
  user: root
  password: 12345678
messages:
  NO_ACCESS: '§cНет доступа'
  HOME_DOESNT_EXIST: '§cУ вас нет дома'
  PLAYER_DOESNT_EXIST: '§cДанный игрок не найден!'
  PLAYER_ALREADY_HAS_ACCESS: '§cУ данного игрока уже есть доступ в ваш дом!'
  PLAYER_DOESNT_HAVE_ACCESS: '§cУ данного игрока и так не доступа в ваш дом'
  SUCCESS: '§aУспешно!'
  HELP_HOME: '§7/home - телепортация домой'
  HELP_RELOAD: '§7/home reload - обновление конфига плагина'
  HELP_DELETE: '§7/home delete - удаление дома'
  HELP_INVITE: '§7/home invite <nick> - выдать доступ к дому игроку'
  HELP_UNINVITE: '§7/home uninvite <nick> - убрать доступ к дому игроку'
  HELP_LIST: '§7/home list - список доступных домов'
  HELP_ILIST: '§7/home ilist - список приглашенных к себе домой'
  HELP_PUBLIC: '§7/home public - сделать дом общедоступным'
  HELP_PRIVATE: '§7/home private - сделать дом приватным'
  LIST: '§eДоступные дома: '
  ILIST: '§eИгроки с доступом в ваш дом: '
  INVITED: '§aВы были приглашены в дом %nick%'
  UNINVITED: '§cВам ограничили доступ в дом %nick%'
  PUBLIC: '§aВы сделали дом публичным'
  PRIVATE: '§aВы сделали дом приватным'